version: '3.7'

services:
 next-steps-db:
  image: mcr.microsoft.com/mssql/server:2019-latest
  volumes:
   - ./sql-volume:/var/opt/mssql/data
  environment:
   ACCEPT_EULA: 'Y'
   SA_PASSWORD: 'Password1994'
   MSSQL_PID: 'Developer'
  ports:
   - '9999:1433'

 next-steps-api:
  build: .
  restart: always
  environment:
   ConnectionString: 'Server=next-steps-db;Database=NextStepsDb;User=sa;Password=Password1994'
  ports:
   - '8080:80'
  depends_on:
   - next-steps-db